[package]
name = "naive-parsec"
version = "0.1.0"
authors = ["codgician <15964984+codgician@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
